pub(crate) mod home_page;
pub(crate) mod single_post_controller;
pub(crate) mod category_controller;
pub(crate) mod pagination_controller;
pub(crate) mod posts_controller;
pub(crate) mod pagination_logic;
pub(crate) mod authentication;
pub(crate) mod sample;
pub(crate) mod common_controller;
